# Generated by Django 5.1.6 on 2025-02-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listings',
            old_name='discription',
            new_name='description',
        ),
    ]
