# Generated by Django 5.1.6 on 2025-02-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listings'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.FloatField(default=0),
        ),
    ]
